# Generated by Django 5.2.6 on 2025-09-19 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.CharField(verbose_name=255)),
                ('data_inicio', models.DateField()),
                ('data_termino', models.DateField()),
                ('finalizada', models.BooleanField()),
            ],
        ),
    ]
